export default {
  'attestations': 'アテステーション',
  'sbom': 'SBOM',
  'slsa': 'SLSA',
  'provenance': 'イメージプロビナンス',
  'fips': 'FIPS',
  'stig': 'STIG',
  'cis': 'CIS ベンチマーク',
  'cves': 'CVE',
  'vex': 'VEX',
  'sscs': 'ソフトウェアサプライチェーンセキュリティ',
  'ssdlc': 'SSDLC',
  'distroless': 'Distroless イメージ',
  'glibc-musl': 'glibc と musl',
  'immutability': 'イミュータビリティ',
  'hardening': 'ハードニング',
  'digests': 'イメージダイジェスト',
  'signatures': 'コード署名',
}
